[supervisord]
nodaemon=true
user=settle
logfile=/var/log/supervisor/supervisord.log
pidfile=/tmp/supervisord.pid
loglevel=info

[program:transaction-engine]
command=/usr/local/bin/node /app/dist/transaction-engine.js
directory=/app
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
environment=PORT="8080",SERVICE_NAME="transaction-engine"

[program:smart-contracts]
command=/usr/local/bin/node /app/dist/smart-contracts.js
directory=/app
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
environment=PORT="8082",SERVICE_NAME="smart-contracts"

[program:tokenization-engine]
command=/usr/local/bin/node /app/dist/tokenization-engine.js
directory=/app
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
environment=PORT="8089",SERVICE_NAME="tokenization-engine"

[program:dex]
command=/usr/local/bin/node /app/dist/dex.js
directory=/app
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
environment=PORT="8088",SERVICE_NAME="dex"
