[supervisord]
nodaemon=true
user=horizon
logfile=/var/log/supervisor/supervisord.log
pidfile=/tmp/supervisord.pid
loglevel=info

[program:blockchain-oracle]
command=/usr/local/bin/node /app/dist/blockchain-oracle.js
directory=/app
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
environment=PORT="8086",SERVICE_NAME="blockchain-oracle"

[program:market-data]
command=/usr/local/bin/node /app/dist/market-data.js
directory=/app
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
environment=PORT="8085",SERVICE_NAME="market-data"
