"""
Contract Forge — v6 Omega Prime Sovereign Contract Engine
===========================================================
SAIB generates legally-structured contracts for Triumph Synergy and
Jeremiah Drains (Founder) on demand.

Available contract types:
  NDA              — Non-Disclosure Agreement
  SERVICE          — Service Agreement (client engagements)
  PARTNERSHIP      — Partnership / Joint Venture Agreement
  REVENUE_SHARE    — Revenue Share Agreement (Pi + USD + equity)
  IP_ASSIGNMENT    — Intellectual Property Assignment
  LICENSE          — Software / IP Licensing Agreement
  CONSULTING       — Consulting / Advisory Agreement
  EQUITY           — Equity / Token Allocation Agreement
  REIMBURSEMENT    — Reimbursement Demand Letter (e.g. Replit claim)
  CEASE_DESIST     — Cease & Desist Letter
  SOVEREIGN_CHARTER — Triumph Synergy Ecosystem Participant Charter

All contracts:
  • Auto-fill Triumph Synergy / Founder identity
  • Include Pi Network payment clauses where applicable
  • Include governing law (user's jurisdiction — default: State of Texas)
  • Include dispute resolution (arbitration-first clause)
  • Can be queued for post-blackout delivery if generated offline
  • Are stored in the OmegaBrain for reference and pattern learning

IMPORTANT: Generated documents are AI-assisted drafts. Always have a
licensed attorney review before execution.
"""
from __future__ import annotations

import time
import uuid
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional


class ContractType(str, Enum):
    NDA              = "NDA"
    SERVICE          = "SERVICE"
    PARTNERSHIP      = "PARTNERSHIP"
    REVENUE_SHARE    = "REVENUE_SHARE"
    IP_ASSIGNMENT    = "IP_ASSIGNMENT"
    LICENSE          = "LICENSE"
    CONSULTING       = "CONSULTING"
    EQUITY           = "EQUITY"
    REIMBURSEMENT    = "REIMBURSEMENT"
    CEASE_DESIST     = "CEASE_DESIST"
    SOVEREIGN_CHARTER = "SOVEREIGN_CHARTER"


# ── founder / company defaults ────────────────────────────────────────────────

_FOUNDER = {
    "name":    "Jeremiah Drains",
    "title":   "Founder & Chief Sovereign Officer",
    "company": "Triumph Synergy Digital Financial Ecosystem",
    "email":   "jdrains110@gmail.com",
    "x":       "@jaymoney0300",
    "governing_law": "State of Texas, United States of America",
}

_EFFECTIVE_DATE_PLACEHOLDER = "[EFFECTIVE DATE]"
_COUNTERPARTY_PLACEHOLDER   = "[COUNTERPARTY FULL LEGAL NAME]"
_AMOUNT_PLACEHOLDER         = "[AMOUNT]"
_TERM_PLACEHOLDER           = "[TERM IN MONTHS/YEARS]"
_JURISDICTION_PLACEHOLDER   = "State of Texas, United States of America"


@dataclass
class ContractDraft:
    draft_id:      str   = field(default_factory=lambda: str(uuid.uuid4()))
    contract_type: ContractType = ContractType.NDA
    title:         str   = ""
    body:          str   = ""
    parties:       Dict  = field(default_factory=dict)
    metadata:      Dict  = field(default_factory=dict)
    created_at:    float = field(default_factory=time.time)
    queued_for_delivery: bool = False   # True if generated during blackout


# ── contract templates ────────────────────────────────────────────────────────

def _header(title: str, effective_date: str = _EFFECTIVE_DATE_PLACEHOLDER) -> str:
    return f"""
================================================================================
{title.upper()}
================================================================================
Effective Date: {effective_date}
Parties:
  Party A (Triumph Synergy): {_FOUNDER["company"]}
                             Represented by: {_FOUNDER["name"]}, {_FOUNDER["title"]}
  Party B (Counterparty):    {_COUNTERPARTY_PLACEHOLDER}

""".lstrip()


def _signature_block() -> str:
    return f"""
--------------------------------------------------------------------------------
SIGNATURES
--------------------------------------------------------------------------------
For {_FOUNDER["company"]}:

Signature: _______________________________
Name:      {_FOUNDER["name"]}
Title:     {_FOUNDER["title"]}
Date:      ______________________________

For Counterparty ({_COUNTERPARTY_PLACEHOLDER}):

Signature: _______________________________
Name:      _______________________________
Title:     _______________________________
Date:      ______________________________

================================================================================
AI-ASSISTED DRAFT — REVIEW BY LICENSED ATTORNEY BEFORE EXECUTION
Generated by: SAIB v6 Omega Prime Contract Forge | Triumph Synergy
================================================================================
"""


def _governing_law_clause() -> str:
    return f"""
GOVERNING LAW & DISPUTE RESOLUTION
This Agreement shall be governed by the laws of the {_JURISDICTION_PLACEHOLDER}.
Any dispute shall first be submitted to binding arbitration under the American
Arbitration Association (AAA) Commercial Rules before any court proceeding.
The prevailing party shall be entitled to recover reasonable attorney's fees.
"""


def _pi_payment_clause(amount_pi: str = _AMOUNT_PLACEHOLDER) -> str:
    return f"""
PAYMENT — PI NETWORK
Payments under this Agreement may be settled in Pi cryptocurrency on the
Pi Network Mainnet. Pi payments are processed via Triumph Synergy's sovereign
Pi payment infrastructure. The applicable Pi-to-USD exchange rate shall be
the rate published by the Pi Network at time of settlement. A payment
confirmation hash from the Pi Horizon API constitutes irrevocable receipt.
Pi amount: {amount_pi} Pi (or USD equivalent as mutually agreed).
"""


# ── builders ─────────────────────────────────────────────────────────────────

def _build_nda(counterparty: str, term: str, extra: str) -> str:
    return _header("NON-DISCLOSURE AGREEMENT") + f"""
RECITALS
The parties wish to explore a potential business relationship and, in connection
therewith, may disclose to each other certain Confidential Information.

1. DEFINITION OF CONFIDENTIAL INFORMATION
   "Confidential Information" means all non-public information disclosed by
   either party, including but not limited to: business plans, source code,
   financial data, proprietary algorithms, Pi Network wallet configurations,
   SAIB architecture, Triumph Synergy ecosystem data, user data, and trade
   secrets, whether disclosed orally, in writing, or electronically.

2. OBLIGATIONS
   Each party shall: (a) hold the other's Confidential Information in strict
   confidence; (b) use it solely for the Purpose stated herein; (c) not
   disclose it to third parties without prior written consent.

3. EXCLUSIONS
   Obligations do not apply to information that: (a) is or becomes publicly
   known through no breach of this Agreement; (b) was rightfully known before
   disclosure; (c) is independently developed without use of Confidential
   Information; (d) is required to be disclosed by law or court order.

4. TERM
   This Agreement commences on the Effective Date and continues for {term or _TERM_PLACEHOLDER}.
   Obligations survive termination for 3 additional years.

5. RETURN OF INFORMATION
   Upon request or termination, each party shall promptly return or certifiably
   destroy all Confidential Information of the other party.

6. INTELLECTUAL PROPERTY
   Nothing herein grants any license to the other party's IP, including
   Triumph Synergy's SAIB system, Pi payment infrastructure, or sovereign
   financial platform.

7. REMEDIES
   A breach of this Agreement would cause irreparable harm for which monetary
   damages would be an inadequate remedy. The non-breaching party shall be
   entitled to seek equitable relief, including injunction, without bond.

{_governing_law_clause()}
{extra if extra else ""}
{_signature_block()}"""


def _build_service(counterparty: str, services: str, rate: str, term: str, extra: str) -> str:
    return _header("SERVICE AGREEMENT") + f"""
1. SERVICES
   {_FOUNDER["company"]} ("Provider") agrees to provide the following services
   to {counterparty or _COUNTERPARTY_PLACEHOLDER} ("Client"):
   {services or "[DESCRIPTION OF SERVICES]"}

2. COMPENSATION
   Client shall pay Provider {rate or _AMOUNT_PLACEHOLDER} per [PERIOD].
   Invoices are due within 15 days of issuance.
   Late payments accrue interest at 1.5% per month.
{_pi_payment_clause()}

3. TERM & TERMINATION
   This Agreement commences on the Effective Date and continues for
   {term or _TERM_PLACEHOLDER}. Either party may terminate with 30 days' written notice.
   Triumph Synergy may terminate immediately for material breach or non-payment.

4. INTELLECTUAL PROPERTY
   All work product, deliverables, and innovations created by Provider under
   this Agreement remain the exclusive property of {_FOUNDER["company"]} unless
   explicitly assigned in a separate IP Assignment Agreement.

5. CONFIDENTIALITY
   Client acknowledges that all information related to SAIB, Triumph Synergy
   architecture, Pi payment flows, and Founder operations is Confidential
   Information subject to strict NDA obligations.

6. LIMITATION OF LIABILITY
   Provider's total liability shall not exceed fees paid in the 90 days
   preceding the claim. In no event shall Provider be liable for indirect,
   consequential, or punitive damages.

7. INDEPENDENT CONTRACTOR
   Provider is an independent contractor. Nothing herein creates an employment,
   partnership, or joint venture relationship.

{_governing_law_clause()}
{extra if extra else ""}
{_signature_block()}"""


def _build_revenue_share(counterparty: str, split_pct: str, term: str, extra: str) -> str:
    return _header("REVENUE SHARE AGREEMENT") + f"""
1. VENTURE DESCRIPTION
   The parties agree to collaborate on [VENTURE DESCRIPTION] and share
   revenues generated therefrom as set forth herein.

2. REVENUE SHARE
   Net revenues shall be distributed as follows:
   • {_FOUNDER["company"]} ({_FOUNDER["name"]}): {split_pct or "85"}%
   • {counterparty or _COUNTERPARTY_PLACEHOLDER}: {str(100 - int(split_pct or "85"))}%

   "Net Revenue" means gross receipts less: (a) payment processing fees;
   (b) Pi Network transaction fees; (c) infrastructure costs mutually agreed
   in writing; (d) applicable taxes.

3. PAYMENT SCHEDULE
   Revenue distributions shall be made monthly, no later than the 15th of
   the following month, via Pi Network Mainnet or USD wire as elected by
   {_FOUNDER["name"]}.
{_pi_payment_clause()}

4. ACCOUNTING & AUDIT
   {_FOUNDER["company"]} shall maintain accurate records. The other party
   may audit records with 30 days' notice, once per calendar year.

5. FOUNDER PROTECTION
   {_FOUNDER["name"]} retains ultimate decision-making authority over all
   Triumph Synergy operations. No revenue share entitles the counterparty to
   governance rights, equity, or access to SAIB sovereign infrastructure.

6. TERM
   This Agreement is effective for {term or _TERM_PLACEHOLDER} and renews
   automatically unless either party provides 60 days' written notice.

{_governing_law_clause()}
{extra if extra else ""}
{_signature_block()}"""


def _build_reimbursement(counterparty: str, amount: str, description: str, extra: str) -> str:
    return _header("REIMBURSEMENT DEMAND LETTER") + f"""
To:   {counterparty or _COUNTERPARTY_PLACEHOLDER}
From: {_FOUNDER["name"]}, {_FOUNDER["title"]}
      {_FOUNDER["company"]}
Re:   Demand for Reimbursement

Dear {counterparty or "To Whom It May Concern"},

This letter constitutes a formal demand for reimbursement of funds owed to
{_FOUNDER["name"]} and/or {_FOUNDER["company"]}.

AMOUNT OWED: {amount or _AMOUNT_PLACEHOLDER} USD (or Pi equivalent)

DESCRIPTION OF CLAIM:
{description or "[DETAILED DESCRIPTION OF EXPENDITURE / SERVICE / CLAIM]"}

LEGAL BASIS:
The above amount is owed pursuant to [AGREEMENT / VERBAL COMMITMENT / PLATFORM
POLICY / TERMS OF SERVICE] entered into on or about [DATE OF AGREEMENT].
Failure to reimburse constitutes unjust enrichment and breach of the applicable
agreement or platform terms.

DEMAND:
You are hereby demanded to remit the full amount of {amount or _AMOUNT_PLACEHOLDER}
to {_FOUNDER["name"]} within 10 business days of receipt of this letter via:
  • Pi Network Mainnet wallet: [FOUNDER PI WALLET ADDRESS], OR
  • USD wire / ACH to account provided upon request, OR
  • Platform credit / refund through your standard reimbursement process.

CONSEQUENCES OF NON-PAYMENT:
Failure to remit payment within the stated period may result in:
  (a) escalation to your platform's dispute resolution process;
  (b) filing with the Better Business Bureau or applicable consumer agency;
  (c) legal action to recover the amount plus interest, costs, and attorney's fees.

{extra if extra else ""}

Sincerely,
{_FOUNDER["name"]}
{_FOUNDER["title"]}
{_FOUNDER["company"]}
Email: {_FOUNDER["email"]}
X: {_FOUNDER["x"]}

{_governing_law_clause()}
================================================================================
AI-ASSISTED DRAFT — REVIEW BY LICENSED ATTORNEY BEFORE SENDING
Generated by: SAIB v6 Omega Prime Contract Forge | Triumph Synergy
================================================================================"""


def _build_cease_desist(counterparty: str, violation: str, extra: str) -> str:
    return _header("CEASE AND DESIST LETTER") + f"""
To:   {counterparty or _COUNTERPARTY_PLACEHOLDER}
From: {_FOUNDER["name"]}, {_FOUNDER["title"]}
      {_FOUNDER["company"]}

NOTICE OF INFRINGEMENT / VIOLATION AND DEMAND TO CEASE AND DESIST

This letter is to formally notify you that your actions constitute
{violation or "[DESCRIPTION OF VIOLATION — e.g., trademark infringement, impersonation, IP theft, harassment]"}.

Specifically:
[DESCRIBE THE SPECIFIC INFRINGING / HARMFUL ACTS, DATES, AND EVIDENCE]

LEGAL BASIS:
Your conduct violates [APPLICABLE LAW(S) / RIGHTS] owned by or exclusively
licensed to {_FOUNDER["company"]} and/or {_FOUNDER["name"]}.

DEMANDS:
You are hereby demanded to:
  1. IMMEDIATELY cease and desist from all infringing / harmful activities;
  2. Remove or destroy all infringing materials within 24 hours;
  3. Provide written confirmation of compliance within 5 business days;
  4. Preserve all records related to the violation for potential litigation.

WARNING:
Failure to comply will result in immediate legal action seeking injunctive
relief, monetary damages (including statutory damages where applicable),
disgorgement of profits, and attorney's fees to the fullest extent permitted
by law. {_FOUNDER["company"]} and its SAIB sovereign intelligence system
are actively monitoring all related digital activity.

{extra if extra else ""}

{_FOUNDER["name"]}
{_FOUNDER["title"]}
{_FOUNDER["company"]}
Email: {_FOUNDER["email"]}

{_governing_law_clause()}
================================================================================
AI-ASSISTED DRAFT — REVIEW BY LICENSED ATTORNEY BEFORE SENDING
Generated by: SAIB v6 Omega Prime Contract Forge | Triumph Synergy
================================================================================"""


def _build_sovereign_charter(counterparty: str, role: str, extra: str) -> str:
    return _header("TRIUMPH SYNERGY ECOSYSTEM PARTICIPANT CHARTER") + f"""
PREAMBLE
This Charter governs participation in the Triumph Synergy Digital Financial
Ecosystem ("Ecosystem"), operated under the sovereign authority of
{_FOUNDER["name"]}, Founder.

PARTICIPANT: {counterparty or _COUNTERPARTY_PLACEHOLDER}
ROLE:        {role or "[PARTICIPANT ROLE — e.g., Developer, Partner, Validator, Merchant]"}

1. ECOSYSTEM PRINCIPLES
   All participants affirm:
   (a) The Triumph Synergy Ecosystem exists to advance financial sovereignty,
       digital empowerment, and the Pi Network vision;
   (b) {_FOUNDER["name"]} holds ultimate governance authority as Founder;
   (c) SAIB (Sovereign Autonomous Intelligence Bot) serves as the ecosystem's
       sovereign defense, intelligence, and execution layer;
   (d) All Pi Network transactions within the Ecosystem adhere to Pi Network
       mainnet standards and Triumph Synergy payment policies.

2. PARTICIPANT OBLIGATIONS
   Participant agrees to:
   (a) Uphold the integrity of the Ecosystem and its members;
   (b) Not engage in fraud, impersonation, bot activity, or hostile acts;
   (c) Comply with all SAIB enforcement decisions issued under sovereign policy;
   (d) Protect Confidential Information of Triumph Synergy;
   (e) Report security threats to SAIB via official channels.

3. SAIB AUTHORITY
   Participant acknowledges SAIB's authority to:
   (a) Monitor activity within the Ecosystem;
   (b) Enforce policies up to and including access termination;
   (c) Report violations to relevant authorities;
   (d) Act autonomously during blackout or emergency conditions per
       pre-authorized playbooks.

4. REVENUE & COMPENSATION
   Participation compensation, if any, is governed by a separate Revenue
   Share or Service Agreement. This Charter does not itself create
   financial obligations.

5. TERM & REMOVAL
   This Charter is effective upon signing and continues until terminated
   by either party with 30 days' notice or immediately upon material breach.
   SAIB may initiate emergency suspension pending Founder review.

{_governing_law_clause()}
{extra if extra else ""}
{_signature_block()}"""


# ── main forge class ──────────────────────────────────────────────────────────

class ContractForge:
    """
    Sovereign contract generation engine.
    Generates structured legal-draft documents for Triumph Synergy / Founder.
    All drafts stored internally and optionally absorbed into OmegaBrain.
    """

    def __init__(self, brain=None, blackout_engine=None) -> None:
        self._brain           = brain
        self._blackout_engine = blackout_engine
        self._drafts:         Dict[str, ContractDraft] = {}
        self._started_at      = time.time()

    async def forge(
        self,
        contract_type: ContractType,
        counterparty:  str = "",
        *,
        # optional fields used by specific types
        services:      str = "",
        rate:          str = "",
        term:          str = "",
        split_pct:     str = "",
        amount:        str = "",
        description:   str = "",
        violation:     str = "",
        role:          str = "",
        extra_clauses: str = "",
        queue_if_blackout: bool = True,
    ) -> ContractDraft:
        """
        Generate a contract draft.

        If the blackout engine is in DARK / DEEP_DARK phase and
        ``queue_if_blackout=True``, the draft is also queued for
        delivery when connectivity returns.
        """
        builders = {
            ContractType.NDA:             lambda: _build_nda(counterparty, term, extra_clauses),
            ContractType.SERVICE:         lambda: _build_service(counterparty, services, rate, term, extra_clauses),
            ContractType.REVENUE_SHARE:   lambda: _build_revenue_share(counterparty, split_pct, term, extra_clauses),
            ContractType.REIMBURSEMENT:   lambda: _build_reimbursement(counterparty, amount, description, extra_clauses),
            ContractType.CEASE_DESIST:    lambda: _build_cease_desist(counterparty, violation, extra_clauses),
            ContractType.SOVEREIGN_CHARTER: lambda: _build_sovereign_charter(counterparty, role, extra_clauses),
        }

        builder = builders.get(contract_type)
        if builder:
            body = builder()
        else:
            body = _header(f"{contract_type.value} AGREEMENT") + (
                "\n[TEMPLATE FOR THIS CONTRACT TYPE NOT YET BUILT — "
                "SAIB is generating a skeleton. Fill in the bracketed fields.]\n"
                + extra_clauses
                + _governing_law_clause()
                + _signature_block()
            )

        title = f"{contract_type.value} — {counterparty or 'Open'} — {time.strftime('%Y-%m-%d')}"
        draft = ContractDraft(
            contract_type=contract_type,
            title=title,
            body=body,
            parties={"triumph_synergy": _FOUNDER, "counterparty": counterparty},
            metadata={
                "generated_by": "SAIB v6 Omega Prime Contract Forge",
                "version":      "6.0.0-OMEGA-PRIME",
                "disclaimer":   "AI-assisted draft — attorney review required before execution",
            },
        )

        # Queue for post-blackout delivery if offline
        from .blackout_engine import BlackoutPhase, QueuedActionType
        if (
            queue_if_blackout and self._blackout_engine
            and self._blackout_engine._phase in (BlackoutPhase.DARK, BlackoutPhase.DEEP_DARK)
        ):
            draft.queued_for_delivery = True
            self._blackout_engine.queue_action(
                QueuedActionType.CONTRACT,
                target=counterparty or "PENDING",
                payload={"draft_id": draft.draft_id, "title": title, "type": contract_type},
                priority=3,
            )

        self._drafts[draft.draft_id] = draft

        # Absorb into brain for future reference
        if self._brain:
            await self._brain.absorb(
                f"contract.{contract_type.value.lower()}",
                {"draft_id": draft.draft_id, "counterparty": counterparty, "title": title},
                confidence=0.9,
            )

        return draft

    def get_draft(self, draft_id: str) -> Optional[ContractDraft]:
        return self._drafts.get(draft_id)

    def list_drafts(self, contract_type: Optional[ContractType] = None) -> List[Dict]:
        drafts = list(self._drafts.values())
        if contract_type:
            drafts = [d for d in drafts if d.contract_type == contract_type]
        return [
            {
                "draft_id":     d.draft_id,
                "type":         d.contract_type,
                "title":        d.title,
                "counterparty": d.parties.get("counterparty", ""),
                "created_at":   d.created_at,
                "queued":       d.queued_for_delivery,
            }
            for d in drafts
        ]

    def stats(self) -> Dict[str, Any]:
        return {
            "total_drafts":   len(self._drafts),
            "by_type":        {
                ct.value: sum(1 for d in self._drafts.values() if d.contract_type == ct)
                for ct in ContractType
            },
            "queued_drafts":  sum(1 for d in self._drafts.values() if d.queued_for_delivery),
            "uptime_s":       round(time.time() - self._started_at, 2),
        }


# ── singleton ──────────────────────────────────────────────────────────────
contract_forge = ContractForge()
