[supervisord]
nodaemon=true
user=govern
logfile=/var/log/supervisor/supervisord.log
pidfile=/tmp/supervisord.pid
loglevel=info

[program:compliance]
command=/usr/local/bin/node /app/dist/compliance.js
directory=/app
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
environment=PORT="8087",SERVICE_NAME="compliance"

[program:judicial-monitor]
command=/usr/local/bin/node /app/dist/judicial-monitor.js
directory=/app
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
environment=PORT="8096",SERVICE_NAME="judicial-monitor"

[program:central-node]
command=/usr/local/bin/node /app/dist/central-node.js
directory=/app
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
environment=SERVICE_NAME="central-node"

[program:scp-upgrader]
command=/usr/local/bin/node /app/dist/scp-upgrader.js
directory=/app
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
environment=PORT="8083",SERVICE_NAME="scp-upgrader"
