#!/usr/bin/env bash
# =============================================================================
# Triumph Synergy — Sovereign Mesh Key Generator
# =============================================================================
# Generates WireGuard Curve25519 keypairs and pre-shared keys for all
# 10 nodes on the sovereign mesh (10.13.37.0/24).
#
# Output: ./mesh-keys/<node>/{private.key, public.key, psk.key}
# These should be mounted into containers or stored in Docker volumes.
#
# Usage:
#   chmod +x scripts/generate-mesh-keys.sh
#   ./scripts/generate-mesh-keys.sh [output-dir]
#
# After generation, copy keys to Docker volume with:
#   ./scripts/generate-mesh-keys.sh
#   docker create --name tmp-key-loader -v triumph_mesh_keys:/app/keys alpine sleep 1
#   docker cp ./mesh-keys/. tmp-key-loader:/app/keys/
#   docker rm tmp-key-loader
# =============================================================================

set -euo pipefail

OUT_DIR="${1:-./mesh-keys}"

# Check for wg tool
if ! command -v wg &>/dev/null; then
    echo "ERROR: 'wg' not found. Install wireguard-tools:"
    echo "  macOS:  brew install wireguard-tools"
    echo "  Ubuntu: sudo apt install wireguard-tools"
    exit 1
fi

# Mesh nodes: <name> <mesh_ip>
declare -A NODES=(
    ["hub"]="10.13.37.1"
    ["app"]="10.13.37.10"
    ["nginx"]="10.13.37.11"
    ["apex-services"]="10.13.37.12"
    ["smb"]="10.13.37.13"
    ["quantum"]="10.13.37.14"
    ["settlement"]="10.13.37.15"
    ["pi-node"]="10.13.37.16"
    ["governance"]="10.13.37.17"
    ["vault"]="10.13.37.18"
)

echo ""
echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║   Triumph Synergy Sovereign Mesh — WireGuard Key Generator       ║"
echo "║   Cipher: ChaCha20-Poly1305 + Curve25519 ECDH + 256-bit PSK     ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""

mkdir -p "${OUT_DIR}"
chmod 700 "${OUT_DIR}"

# ── Generate keypairs ─────────────────────────────────────────────────────────
echo "Generating Curve25519 keypairs for all mesh nodes..."
echo ""

declare -A PUBLIC_KEYS

for NODE in "${!NODES[@]}"; do
    NODE_DIR="${OUT_DIR}"
    PRIV="${NODE_DIR}/${NODE}_private.key"
    PUB="${NODE_DIR}/${NODE}_public.key"

    if [ ! -f "${PRIV}" ]; then
        wg genkey > "${PRIV}"
        chmod 600 "${PRIV}"
    fi
    wg pubkey < "${PRIV}" > "${PUB}"
    PUBLIC_KEYS["${NODE}"]="$(cat ${PUB})"
    echo "  [${NODE}]  ${NODES[$NODE]}  →  $(cat ${PUB})"
done

echo ""

# ── Generate PSKs (one per peer, between hub and each node) ──────────────────
echo "Generating Pre-Shared Keys (256-bit symmetric, per peer)..."
echo ""
for NODE in "${!NODES[@]}"; do
    if [ "${NODE}" == "hub" ]; then continue; fi
    PSK="${OUT_DIR}/psk_${NODE}.key"
    if [ ! -f "${PSK}" ]; then
        wg genpsk > "${PSK}"
        chmod 600 "${PSK}"
    fi
    echo "  PSK [hub ↔ ${NODE}]: $(cat ${PSK})"
done

echo ""

# ── Write hub's wg-sovereign.conf ─────────────────────────────────────────────
HUB_CONF="${OUT_DIR}/wg-sovereign.conf"
HUB_PRIVATE="$(cat ${OUT_DIR}/hub_private.key)"

echo "Writing hub config: ${HUB_CONF}"

cat > "${HUB_CONF}" << WGEOF
# Triumph Synergy Sovereign Mesh Hub — WireGuard Config
# Generated by: scripts/generate-mesh-keys.sh
# DO NOT COMMIT to version control (contains private keys)

[Interface]
PrivateKey = ${HUB_PRIVATE}
Address = 10.13.37.1/24
ListenPort = 51820
PostUp   = iptables -A FORWARD -i wg-sovereign -j ACCEPT; iptables -A FORWARD -o wg-sovereign -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg-sovereign -j ACCEPT; iptables -D FORWARD -o wg-sovereign -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

WGEOF

for NODE in "${!NODES[@]}"; do
    if [ "${NODE}" == "hub" ]; then continue; fi
    PSK_LINE=""
    PSK_FILE="${OUT_DIR}/psk_${NODE}.key"
    if [ -f "${PSK_FILE}" ]; then
        PSK_LINE="PresharedKey = $(cat ${PSK_FILE})"
    fi

    cat >> "${HUB_CONF}" << PEEREOF
# Peer: ${NODE}  (${NODES[$NODE]})
[Peer]
PublicKey = $(cat ${OUT_DIR}/${NODE}_public.key)
${PSK_LINE}
AllowedIPs = ${NODES[$NODE]}/32

PEEREOF
done

chmod 600 "${HUB_CONF}"

# ── Write per-node client configs ─────────────────────────────────────────────
echo ""
echo "Writing per-node client configs..."
HUB_PUB="$(cat ${OUT_DIR}/hub_public.key)"

for NODE in "${!NODES[@]}"; do
    if [ "${NODE}" == "hub" ]; then continue; fi
    NODE_CONF="${OUT_DIR}/client_${NODE}.conf"
    NODE_PRIV="$(cat ${OUT_DIR}/${NODE}_private.key)"
    PSK_LINE=""
    PSK_FILE="${OUT_DIR}/psk_${NODE}.key"
    if [ -f "${PSK_FILE}" ]; then
        PSK_LINE="PresharedKey = $(cat ${PSK_FILE})"
    fi

    cat > "${NODE_CONF}" << CLIENTEOF
# Triumph Sovereign Mesh — Client Config for: ${NODE}  (${NODES[$NODE]})
# Generated by: scripts/generate-mesh-keys.sh
# DO NOT COMMIT to version control

[Interface]
PrivateKey = ${NODE_PRIV}
Address = ${NODES[$NODE]}/24
DNS = 10.13.37.1

[Peer]
# Triumph Sovereign Mesh Hub
PublicKey = ${HUB_PUB}
${PSK_LINE}
AllowedIPs = 10.13.37.0/24
Endpoint = triumph-sovereign-mesh-hub:51820
PersistentKeepalive = 25
CLIENTEOF

    chmod 600 "${NODE_CONF}"
    echo "  Written: ${NODE_CONF}"
done

echo ""
echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║   Key Generation Complete                                        ║"
echo "╠══════════════════════════════════════════════════════════════════╣"
echo "║   Output: ${OUT_DIR}"
echo "║"
echo "║   Next steps:"
echo "║   1. Load keys into Docker volume:"
echo "║      docker create --name tmp-key-loader -v triumph_mesh_keys:/app/keys alpine sleep 1"
echo "║      docker cp ${OUT_DIR}/. tmp-key-loader:/app/keys/"
echo "║      docker rm tmp-key-loader"
echo "║"
echo "║   2. Start the mesh hub:"
echo "║      docker compose up -d sovereign-mesh-hub"
echo "║"
echo "║   3. Verify mesh status:"
echo "║      curl http://localhost:8200/mesh/status"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "SECURITY: Keep ${OUT_DIR}/ private. Add to .gitignore if not already."
