#!/usr/bin/env bash
# ==========================================================================
# Pi Network Supernode Setup (macOS)
# Mirrors Windows setup intent for:
# - Pi Node TCP ports: 31400-31409
# - Stellar Core/Horizon ports: 11625, 11626, 8000
# - Docker/Pi app firewall allowances
# ==========================================================================

set -euo pipefail

DRY_RUN=false
SKIP_PF=false
SKIP_APP_FW=false

for arg in "$@"; do
  case "$arg" in
    --dry-run)
      DRY_RUN=true
      ;;
    --skip-pf)
      SKIP_PF=true
      ;;
    --skip-app-firewall)
      SKIP_APP_FW=true
      ;;
    *)
      echo "Unknown argument: $arg"
      echo "Usage: $0 [--dry-run] [--skip-pf] [--skip-app-firewall]"
      exit 1
      ;;
  esac
done

PI_PORT_RANGE="31400:31409"
EXTRA_PORTS="11625, 11626, 8000"
ANCHOR_NAME="com.triumph.pi-node"
ANCHOR_FILE="/etc/pf.anchors/${ANCHOR_NAME}"
PF_CONF="/etc/pf.conf"

run_cmd() {
  local cmd="$1"
  if [[ "$DRY_RUN" == "true" ]]; then
    echo "[dry-run] $cmd"
  else
    eval "$cmd"
  fi
}

need_root() {
  if [[ "$DRY_RUN" == "true" ]]; then
    return
  fi
  if [[ "${EUID}" -ne 0 ]]; then
    echo "This setup needs admin privileges. Re-running with sudo..."
    exec sudo bash "$0" "$@"
  fi
}

ensure_line_in_pf_conf() {
  local line="$1"
  if grep -Fq "$line" "$PF_CONF"; then
    echo "pf.conf already has: $line"
  else
    echo "Adding to pf.conf: $line"
    run_cmd "printf '\n%s\n' '$line' >> '$PF_CONF'"
  fi
}

configure_pf() {
  echo "Configuring pf firewall rules for Pi Node and Stellar ports..."

  local anchor_content
  anchor_content=$(cat <<'EOF'
# Triumph Synergy Pi Node / Supernode ports
# Generated by scripts/setup-pi-supernode-macos.sh
pass in inet proto tcp from any to any port { 31400:31409, 11625, 11626, 8000 } keep state
pass out inet proto tcp from any to any port { 31400:31409, 11625, 11626, 8000 } keep state
EOF
)

  if [[ "$DRY_RUN" == "true" ]]; then
    echo "[dry-run] write anchor file: $ANCHOR_FILE"
    echo "$anchor_content"
  else
    printf "%s\n" "$anchor_content" > "$ANCHOR_FILE"
    chmod 644 "$ANCHOR_FILE"
  fi

  ensure_line_in_pf_conf "anchor \"$ANCHOR_NAME\""
  ensure_line_in_pf_conf "load anchor \"$ANCHOR_NAME\" from \"$ANCHOR_FILE\""

  run_cmd "pfctl -f '$PF_CONF'"
  run_cmd "pfctl -e || true"

  if [[ "$DRY_RUN" != "true" ]]; then
    echo "Active pf rules touching Pi ports:"
    pfctl -sr | grep -E '3140[0-9]|11625|11626|8000' || true
  fi
}

configure_app_firewall() {
  local socketfw="/usr/libexec/ApplicationFirewall/socketfilterfw"
  if [[ ! -x "$socketfw" ]]; then
    echo "Application Firewall tool not found at $socketfw, skipping app rules."
    return
  fi

  echo "Configuring macOS Application Firewall allow-list for Docker and Pi apps..."

  local apps=(
    "/Applications/Docker.app"
    "/Applications/Pi Network.app"
    "/Applications/Pi Browser.app"
  )

  for app in "${apps[@]}"; do
    if [[ -d "$app" ]]; then
      run_cmd "'$socketfw' --add '$app' || true"
      run_cmd "'$socketfw' --unblockapp '$app' || true"
      echo "Allowed app: $app"
    else
      echo "App not found (skipped): $app"
    fi
  done
}

print_network_summary() {
  local ip_en0 ip_en1 local_ip
  ip_en0=$(ipconfig getifaddr en0 2>/dev/null || true)
  ip_en1=$(ipconfig getifaddr en1 2>/dev/null || true)
  local_ip="$ip_en0"
  if [[ -z "$local_ip" ]]; then
    local_ip="$ip_en1"
  fi

  echo
  echo "=============================================================="
  echo "Pi Node macOS setup summary"
  echo "=============================================================="
  echo "Ports configured: ${PI_PORT_RANGE}, ${EXTRA_PORTS}"
  echo "Local LAN IP: ${local_ip:-unknown}"
  echo
  echo "Router/NAT forwarding (required for external Pi peers):"
  echo "- TCP 31402 -> ${local_ip:-this-mac}"
  echo "- TCP 31401 -> ${local_ip:-this-mac}"
  echo "- TCP 31403 -> ${local_ip:-this-mac}"
  echo "Optional full range forwarding: TCP 31400-31409"
  echo
  echo "Validation commands:"
  echo "- lsof -nP -iTCP:31402 -sTCP:LISTEN"
  echo "- lsof -nP -iTCP:11626 -sTCP:LISTEN"
  echo "- docker ps --format 'table {{.Names}}\t{{.Ports}}'"
  echo "=============================================================="
}

main() {
  need_root "$@"

  echo "Starting Pi supernode setup for macOS..."
  echo "Flags: dry-run=${DRY_RUN}, skip-pf=${SKIP_PF}, skip-app-firewall=${SKIP_APP_FW}"

  if [[ "$SKIP_PF" != "true" ]]; then
    configure_pf
  else
    echo "Skipping pf firewall setup."
  fi

  if [[ "$SKIP_APP_FW" != "true" ]]; then
    configure_app_firewall
  else
    echo "Skipping Application Firewall app rules."
  fi

  print_network_summary
}

main "$@"
