[supervisord]
nodaemon=true

logfile=/var/log/supervisor/supervisord.log
pidfile=/tmp/supervisord.pid
loglevel=info

[program:prometheus]
user=obs
command=/usr/local/bin/prometheus
  --config.file=/etc/prometheus/prometheus.yml
  --storage.tsdb.path=/prometheus
  --storage.tsdb.retention.time=30d
  --web.enable-lifecycle
  --web.listen-address=0.0.0.0:9090
directory=/prometheus
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:grafana]
user=obs
command=/usr/share/grafana/bin/grafana server
  --homepath=/usr/share/grafana
  --config=/etc/grafana/grafana.ini
  cfg:default.paths.data=/var/lib/grafana
  cfg:default.paths.logs=/var/log/grafana
  cfg:default.paths.plugins=/var/lib/grafana/plugins
  cfg:default.paths.provisioning=/etc/grafana/provisioning
  cfg:default.server.http_port=3000
directory=/usr/share/grafana
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
environment=GF_PATHS_DATA="/var/lib/grafana",GF_PATHS_LOGS="/var/log/grafana",GF_PATHS_PROVISIONING="/etc/grafana/provisioning",GF_SECURITY_ADMIN_PASSWORD="%(ENV_GF_SECURITY_ADMIN_PASSWORD)s"

[program:postgres-exporter]
user=obs
command=/usr/local/bin/postgres_exporter
  --web.listen-address=:9187
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
environment=DATA_SOURCE_NAME="%(ENV_DATA_SOURCE_NAME)s"

[program:redis-exporter]
user=obs
command=/usr/local/bin/redis_exporter
  -redis.addr=%(ENV_REDIS_ADDR)s
  -web.listen-address=:9121
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
