name: Build & Deploy Next.js

on:
    push:
        paths:
            - "tmtt_nextjs/**"
            - ".github/workflows/nextjs-deploy.yml"
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy-vercel:
        name: Deploy Next.js to Vercel
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy to Vercel
              uses: vercel/action@v6
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
                  vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
                  working-directory: tmtt_nextjs
