[supervisord]
nodaemon=true
user=insure
logfile=/var/log/supervisor/supervisord.log
pidfile=/tmp/supervisord.pid
loglevel=info

[unix_http_server]
file=/tmp/supervisor.sock

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:life]
command=/usr/local/bin/uvicorn life:app --host 0.0.0.0 --port 8110 --workers 1 --log-level info
directory=/app
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
environment=PORT="8110",SERVICE_NAME="sovereign-life-insurance"

[program:home]
command=/usr/local/bin/uvicorn home:app --host 0.0.0.0 --port 8111 --workers 1 --log-level info
directory=/app
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
environment=PORT="8111",SERVICE_NAME="sovereign-home-insurance"

[program:health]
command=/usr/local/bin/uvicorn health:app --host 0.0.0.0 --port 8112 --workers 1 --log-level info
directory=/app
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
environment=PORT="8112",SERVICE_NAME="sovereign-health-insurance"

[program:auto]
command=/usr/local/bin/uvicorn auto:app --host 0.0.0.0 --port 8113 --workers 1 --log-level info
directory=/app
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
environment=PORT="8113",SERVICE_NAME="sovereign-auto-insurance"

[program:dental]
command=/usr/local/bin/uvicorn dental:app --host 0.0.0.0 --port 8114 --workers 1 --log-level info
directory=/app
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
environment=PORT="8114",SERVICE_NAME="sovereign-dental-insurance"

[program:vision]
command=/usr/local/bin/uvicorn vision:app --host 0.0.0.0 --port 8115 --workers 1 --log-level info
directory=/app
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
environment=PORT="8115",SERVICE_NAME="sovereign-vision-insurance"

[program:hospital]
command=/usr/local/bin/uvicorn hospital:app --host 0.0.0.0 --port 8116 --workers 1 --log-level info
directory=/app
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
environment=PORT="8116",SERVICE_NAME="sovereign-hospital-network"
